baseURL = "https://www.gbstudio.dev"
languageCode = "en-us"
title = "GB Studio"
theme = "gbstudio"

[markup.goldmark.renderer]
    unsafe= true

[[menu.main]]
    name = "About"
    title = "About"
    url = "/about/"

[[menu.main]]
    name = "Docs"
    title = "Docs"
    url = "/docs/"

[[menu.main]]
    name = "Download"
    title = "Download"
    url = "https://chrismaltby.itch.io/gb-studio"

[[menu.main]]
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/chrismaltby/gb-studio"
